### ISSUE TITLE
[BUG] Error: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by pflannery** [npm/npm-registry-fetch#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error Message
```
Error: Cannot set headers after they are sent to the client
	at new NodeError (node:internal/errors:405:5)
	at ClientRequest.setHeader (node:_http_outgoing:648:11)
	at Agent.addRequest (c:\Users\xxx\.vscode\extensions\pflannery.vscode-versionlens-1.11.0\node_modules\@npmcli\agent\lib\agents.js:178:13)
	at c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\agent-base\dist\index.js:77:31
```

A couple of users of my vscode extension versionlens have recently experienced this [issue](https://gitlab.com/versionlens/vscode-versionlens/-/issues/357) 

Versionlens uses `npm-registry-fetch@17.0.1`. I tracked down this error to be related to a sub dependency of this package `@npmcli/agent v2.2.2` which got installed in a recent update to the package-lock.json file.

The error occurs [here](https://github.com/npm/agent/blob/main/lib/agents.js#L178)

When the users rolled back versionlens they reported the error had gone away but the version they rolled back to also uses `npm-registry-fetch@17.0.1` so its a sub dependency update that is causing the problem.

I'm not sure how to recreate the issue as I can't seem to hit the line of code with the error so it seems to be npm config specific.

I'm wondering if the solution is as simple as adding a check

```js
if (!request.headers.has('connection')) {
    request.headers.set('connection', agent ? 'keep-alive' : 'close')
  }
```

### Expected Behavior

No errors

### Environment

- npm: 10.2.4
- Node: `v18.19.1`
- OS: `Windows_NT x64 10.0.19045`

**Comment by pgsandstrom** [comment]
Hey @pflannery did you ever find a workaround for this? This has blocked me from updating npm-registry-fetch for quite some time now.

**Comment by pflannery** [comment]
@pgsandstrom My workaround was to override the @npmcli/agent package

```json
  "overrides": {
    "@npmcli/agent": "2.0.0"
  },
```

It might be that we don't need this override hack anymore but I haven't tried. I'm still using it.
I will try to remove it in a future versionlens release and see if any users report back issues

**Comment by pgsandstrom** [comment]
This bug is still alive and causing issues, as can be seen in this thread: https://github.com/pgsandstrom/package-json-upgrade/issues/59

Would love a proper fix. I can try to develop a PR if developers can acknowledge that they are interested in it.
