### ISSUE TITLE
[BUG] Syntax error

### ISSUE THREAD

**Issue by ckimy** [npm/npm-registry-fetch#31]
# What / Why
The latest code has a syntax error so that it doesn't work on my node environment (8.10)

## Where
https://github.com/npm/npm-registry-fetch/pull/29/files#diff-b49b5d13952110b509e66f7261ef1c70R38

**Comment by sapeish** [comment]
I get the same syntax error in node 8.17.

```
/usr/local/lib/node_modules/npm-check-updates/node_modules/npm-registry-fetch/check-response.js:38
  } catch {
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm-check-updates/node_modules/npm-registry-fetch/index.js:3:23)
```


`catch {` is expected to be `catch (e) {` I assume.

**Comment by claudiahdz** [comment]
Since v6 `npm-registry-fetch` supports only `"node": ">=10"`.  For support for older versions, use v4.
