### ISSUE TITLE
[BUG] Get started exemple not works "uri.trim is not a function"

### ISSUE THREAD

**Issue by c0ncentus** [npm/npm-registry-fetch#56]
# What / Why
 first exemple don't work because of "trim()

## When

  ```
const npmFetch = require('npm-registry-fetch')
(async ()=>{
    console.log(
        await npmFetch.json('/-/ping')
      )
})()
```
then 

```
TypeError: uri.trim is not a function
    at regFetch (C:\Users\Martin\Desktop\screen\node_modules\npm-registry-fetch\index.js:45:11)
    at Object.<anonymous> (C:\Users\Martin\Desktop\screen\api.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

### Steps to Reproduce
"npm-registry-fetch": "^11.0.0"
with statard nodemodule with nodejs (v16.3)

all my code
```
const npmFetch = require('npm-registry-fetch')
(async ()=>{
    console.log(
        await npmFetch.json('/-/ping')
      )
})()
```

### Expected Behavior
I don't know i'm new to this package so i expecte to fetch maybe some thing on npm registry ....

**Comment by wraithgar** [comment]
Can't duplicate, please provide more info if this is still a problem.


```javascript
$ node
Welcome to Node.js v16.13.2.
Type ".help" for more information.
> const npmFetch = require('npm-registry-fetch')
undefined
> (async ()=>{
...   console.log(
.....       await npmFetch.json('/-/ping')
.....     )
... })()
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 49,
  [Symbol(trigger_async_id_symbol)]: 5,
  [Symbol(destroyed)]: { destroyed: false }
}
> {}
```
